<?php
/**
 * ConsignmentsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ConsignmentsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation cancelConsignmentById
     *
     * Request cancellation of a Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  \Swagger\Client\Model\CancellationRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function cancelConsignmentById($carrier_name, $customer_id, $consignment_id, $body = null)
    {
        list($response) = $this->cancelConsignmentByIdWithHttpInfo($carrier_name, $customer_id, $consignment_id, $body);
        return $response;
    }

    /**
     * Operation cancelConsignmentByIdWithHttpInfo
     *
     * Request cancellation of a Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  \Swagger\Client\Model\CancellationRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelConsignmentByIdWithHttpInfo($carrier_name, $customer_id, $consignment_id, $body = null)
    {
        $returnType = 'string';
        $request = $this->cancelConsignmentByIdRequest($carrier_name, $customer_id, $consignment_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation cancelConsignmentByIdAsync
     *
     * Request cancellation of a Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  \Swagger\Client\Model\CancellationRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelConsignmentByIdAsync($carrier_name, $customer_id, $consignment_id, $body = null)
    {
        return $this->cancelConsignmentByIdAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelConsignmentByIdAsyncWithHttpInfo
     *
     * Request cancellation of a Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  \Swagger\Client\Model\CancellationRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelConsignmentByIdAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $body = null)
    {
        $returnType = 'string';
        $request = $this->cancelConsignmentByIdRequest($carrier_name, $customer_id, $consignment_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelConsignmentById'
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  \Swagger\Client\Model\CancellationRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function cancelConsignmentByIdRequest($carrier_name, $customer_id, $consignment_id, $body = null)
    {
        // verify the required parameter 'carrier_name' is set
        if ($carrier_name === null || (is_array($carrier_name) && count($carrier_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_name when calling cancelConsignmentById'
            );
        }
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling cancelConsignmentById'
            );
        }
        // verify the required parameter 'consignment_id' is set
        if ($consignment_id === null || (is_array($consignment_id) && count($consignment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consignment_id when calling cancelConsignmentById'
            );
        }

        $resourcePath = '/v1/carriers/{carrierName}/customers/{customerId}/consignments/{consignmentId}/cancellationrequests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($carrier_name !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierName' . '}',
                ObjectSerializer::toPathValue($carrier_name),
                $resourcePath
            );
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }
        // path params
        if ($consignment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consignmentId' . '}',
                ObjectSerializer::toPathValue($consignment_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConsignmentById
     *
     * Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Consignment
     */
    public function getConsignmentById($carrier_name, $customer_id, $consignment_id, $label_format = null, $label_size = null)
    {
        list($response) = $this->getConsignmentByIdWithHttpInfo($carrier_name, $customer_id, $consignment_id, $label_format, $label_size);
        return $response;
    }

    /**
     * Operation getConsignmentByIdWithHttpInfo
     *
     * Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Consignment, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConsignmentByIdWithHttpInfo($carrier_name, $customer_id, $consignment_id, $label_format = null, $label_size = null)
    {
        $returnType = '\Swagger\Client\Model\Consignment';
        $request = $this->getConsignmentByIdRequest($carrier_name, $customer_id, $consignment_id, $label_format, $label_size);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Consignment',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getConsignmentByIdAsync
     *
     * Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsignmentByIdAsync($carrier_name, $customer_id, $consignment_id, $label_format = null, $label_size = null)
    {
        return $this->getConsignmentByIdAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $label_format, $label_size)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConsignmentByIdAsyncWithHttpInfo
     *
     * Consignment by Id.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsignmentByIdAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $label_format = null, $label_size = null)
    {
        $returnType = '\Swagger\Client\Model\Consignment';
        $request = $this->getConsignmentByIdRequest($carrier_name, $customer_id, $consignment_id, $label_format, $label_size);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConsignmentById'
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id The consignment identifier (required)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getConsignmentByIdRequest($carrier_name, $customer_id, $consignment_id, $label_format = null, $label_size = null)
    {
        // verify the required parameter 'carrier_name' is set
        if ($carrier_name === null || (is_array($carrier_name) && count($carrier_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_name when calling getConsignmentById'
            );
        }
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling getConsignmentById'
            );
        }
        // verify the required parameter 'consignment_id' is set
        if ($consignment_id === null || (is_array($consignment_id) && count($consignment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consignment_id when calling getConsignmentById'
            );
        }

        $resourcePath = '/v1/carriers/{carrierName}/customers/{customerId}/consignments/{consignmentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($label_format !== null) {
            $queryParams['labelFormat'] = ObjectSerializer::toQueryValue($label_format, null);
        }
        // query params
        if ($label_size !== null) {
            $queryParams['labelSize'] = ObjectSerializer::toQueryValue($label_size, null);
        }

        // path params
        if ($carrier_name !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierName' . '}',
                ObjectSerializer::toPathValue($carrier_name),
                $resourcePath
            );
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }
        // path params
        if ($consignment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consignmentId' . '}',
                ObjectSerializer::toPathValue($consignment_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConsignmentsByParameters
     *
     * Search consignments based on Consignment / Sender / Receiver details
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_reference Consignment Reference (optional)
     * @param  string $consignment_status Consignment Status. Seperate by Comma (,) to search multiple (optional)
     * @param  \DateTime $from_consignment_date_time When searching within a date range, this is the start time in Utc which you want to search from. (optional)
     * @param  \DateTime $to_consignment_date_time When searching within a date range, this is the end time in Utc which you want to search to. (optional)
     * @param  string $barcode Consignment barcode (optional)
     * @param  string $query Fuzzy search query string (optional)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Consignments
     */
    public function getConsignmentsByParameters($carrier_name, $customer_id, $consignment_reference = null, $consignment_status = null, $from_consignment_date_time = null, $to_consignment_date_time = null, $barcode = null, $query = null, $label_format = null, $label_size = null, $skip = '0', $limit = '10')
    {
        list($response) = $this->getConsignmentsByParametersWithHttpInfo($carrier_name, $customer_id, $consignment_reference, $consignment_status, $from_consignment_date_time, $to_consignment_date_time, $barcode, $query, $label_format, $label_size, $skip, $limit);
        return $response;
    }

    /**
     * Operation getConsignmentsByParametersWithHttpInfo
     *
     * Search consignments based on Consignment / Sender / Receiver details
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_reference Consignment Reference (optional)
     * @param  string $consignment_status Consignment Status. Seperate by Comma (,) to search multiple (optional)
     * @param  \DateTime $from_consignment_date_time When searching within a date range, this is the start time in Utc which you want to search from. (optional)
     * @param  \DateTime $to_consignment_date_time When searching within a date range, this is the end time in Utc which you want to search to. (optional)
     * @param  string $barcode Consignment barcode (optional)
     * @param  string $query Fuzzy search query string (optional)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Consignments, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConsignmentsByParametersWithHttpInfo($carrier_name, $customer_id, $consignment_reference = null, $consignment_status = null, $from_consignment_date_time = null, $to_consignment_date_time = null, $barcode = null, $query = null, $label_format = null, $label_size = null, $skip = '0', $limit = '10')
    {
        $returnType = '\Swagger\Client\Model\Consignments';
        $request = $this->getConsignmentsByParametersRequest($carrier_name, $customer_id, $consignment_reference, $consignment_status, $from_consignment_date_time, $to_consignment_date_time, $barcode, $query, $label_format, $label_size, $skip, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Consignments',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getConsignmentsByParametersAsync
     *
     * Search consignments based on Consignment / Sender / Receiver details
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_reference Consignment Reference (optional)
     * @param  string $consignment_status Consignment Status. Seperate by Comma (,) to search multiple (optional)
     * @param  \DateTime $from_consignment_date_time When searching within a date range, this is the start time in Utc which you want to search from. (optional)
     * @param  \DateTime $to_consignment_date_time When searching within a date range, this is the end time in Utc which you want to search to. (optional)
     * @param  string $barcode Consignment barcode (optional)
     * @param  string $query Fuzzy search query string (optional)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsignmentsByParametersAsync($carrier_name, $customer_id, $consignment_reference = null, $consignment_status = null, $from_consignment_date_time = null, $to_consignment_date_time = null, $barcode = null, $query = null, $label_format = null, $label_size = null, $skip = '0', $limit = '10')
    {
        return $this->getConsignmentsByParametersAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_reference, $consignment_status, $from_consignment_date_time, $to_consignment_date_time, $barcode, $query, $label_format, $label_size, $skip, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConsignmentsByParametersAsyncWithHttpInfo
     *
     * Search consignments based on Consignment / Sender / Receiver details
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_reference Consignment Reference (optional)
     * @param  string $consignment_status Consignment Status. Seperate by Comma (,) to search multiple (optional)
     * @param  \DateTime $from_consignment_date_time When searching within a date range, this is the start time in Utc which you want to search from. (optional)
     * @param  \DateTime $to_consignment_date_time When searching within a date range, this is the end time in Utc which you want to search to. (optional)
     * @param  string $barcode Consignment barcode (optional)
     * @param  string $query Fuzzy search query string (optional)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsignmentsByParametersAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_reference = null, $consignment_status = null, $from_consignment_date_time = null, $to_consignment_date_time = null, $barcode = null, $query = null, $label_format = null, $label_size = null, $skip = '0', $limit = '10')
    {
        $returnType = '\Swagger\Client\Model\Consignments';
        $request = $this->getConsignmentsByParametersRequest($carrier_name, $customer_id, $consignment_reference, $consignment_status, $from_consignment_date_time, $to_consignment_date_time, $barcode, $query, $label_format, $label_size, $skip, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConsignmentsByParameters'
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_reference Consignment Reference (optional)
     * @param  string $consignment_status Consignment Status. Seperate by Comma (,) to search multiple (optional)
     * @param  \DateTime $from_consignment_date_time When searching within a date range, this is the start time in Utc which you want to search from. (optional)
     * @param  \DateTime $to_consignment_date_time When searching within a date range, this is the end time in Utc which you want to search to. (optional)
     * @param  string $barcode Consignment barcode (optional)
     * @param  string $query Fuzzy search query string (optional)
     * @param  string $label_format Required format of the label - PDF (optional)
     * @param  string $label_size Required size of the label - A4, FreThermal (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getConsignmentsByParametersRequest($carrier_name, $customer_id, $consignment_reference = null, $consignment_status = null, $from_consignment_date_time = null, $to_consignment_date_time = null, $barcode = null, $query = null, $label_format = null, $label_size = null, $skip = '0', $limit = '10')
    {
        // verify the required parameter 'carrier_name' is set
        if ($carrier_name === null || (is_array($carrier_name) && count($carrier_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_name when calling getConsignmentsByParameters'
            );
        }
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling getConsignmentsByParameters'
            );
        }

        $resourcePath = '/v1/carriers/{carrierName}/customers/{customerId}/consignments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($consignment_reference !== null) {
            $queryParams['consignmentReference'] = ObjectSerializer::toQueryValue($consignment_reference, null);
        }
        // query params
        if ($consignment_status !== null) {
            $queryParams['consignmentStatus'] = ObjectSerializer::toQueryValue($consignment_status, null);
        }
        // query params
        if ($from_consignment_date_time !== null) {
            $queryParams['fromConsignmentDateTime'] = ObjectSerializer::toQueryValue($from_consignment_date_time, 'date-time');
        }
        // query params
        if ($to_consignment_date_time !== null) {
            $queryParams['toConsignmentDateTime'] = ObjectSerializer::toQueryValue($to_consignment_date_time, 'date-time');
        }
        // query params
        if ($barcode !== null) {
            $queryParams['barcode'] = ObjectSerializer::toQueryValue($barcode, null);
        }
        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query, null);
        }
        // query params
        if ($label_format !== null) {
            $queryParams['labelFormat'] = ObjectSerializer::toQueryValue($label_format, null);
        }
        // query params
        if ($label_size !== null) {
            $queryParams['labelSize'] = ObjectSerializer::toQueryValue($label_size, null);
        }
        // query params
        if ($skip !== null) {
            $queryParams['skip'] = ObjectSerializer::toQueryValue($skip, 'int32');
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit, 'int32');
        }

        // path params
        if ($carrier_name !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierName' . '}',
                ObjectSerializer::toPathValue($carrier_name),
                $resourcePath
            );
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postConsignment
     *
     * Upload consignment data.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  \Swagger\Client\Model\ConsignmentRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ConsignmentRequestResponse
     */
    public function postConsignment($carrier_name, $customer_id, $body = null)
    {
        list($response) = $this->postConsignmentWithHttpInfo($carrier_name, $customer_id, $body);
        return $response;
    }

    /**
     * Operation postConsignmentWithHttpInfo
     *
     * Upload consignment data.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  \Swagger\Client\Model\ConsignmentRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ConsignmentRequestResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postConsignmentWithHttpInfo($carrier_name, $customer_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\ConsignmentRequestResponse';
        $request = $this->postConsignmentRequest($carrier_name, $customer_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ConsignmentRequestResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postConsignmentAsync
     *
     * Upload consignment data.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  \Swagger\Client\Model\ConsignmentRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postConsignmentAsync($carrier_name, $customer_id, $body = null)
    {
        return $this->postConsignmentAsyncWithHttpInfo($carrier_name, $customer_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postConsignmentAsyncWithHttpInfo
     *
     * Upload consignment data.
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  \Swagger\Client\Model\ConsignmentRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postConsignmentAsyncWithHttpInfo($carrier_name, $customer_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\ConsignmentRequestResponse';
        $request = $this->postConsignmentRequest($carrier_name, $customer_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postConsignment'
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  \Swagger\Client\Model\ConsignmentRequest $body Consignment data that needs to be stored (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function postConsignmentRequest($carrier_name, $customer_id, $body = null)
    {
        // verify the required parameter 'carrier_name' is set
        if ($carrier_name === null || (is_array($carrier_name) && count($carrier_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_name when calling postConsignment'
            );
        }
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling postConsignment'
            );
        }

        $resourcePath = '/v1/carriers/{carrierName}/customers/{customerId}/consignments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($carrier_name !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierName' . '}',
                ObjectSerializer::toPathValue($carrier_name),
                $resourcePath
            );
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
