<?php
/**
 * ServicesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ServicesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServicesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getServiceLocations
     *
     * Return a list of service locations, optionally filter by location type and/or within a radius of a given point
     *
     * @param  string $carrier_name The carrier ID for which to provide a list of available services. (optional)
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon &amp; radius. (optional)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat &amp; radius. (optional)
     * @param  string $service_location_type The type of service location (e.g. Agent, Depot). (optional)
     * @param  int $radius The distance in metres from the geo point the service point must be within. Requires lat &amp; lon. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ServiceLocations
     */
    public function getServiceLocations($carrier_name = null, $lat = null, $lon = null, $service_location_type = null, $radius = null, $skip = '0', $limit = '10')
    {
        list($response) = $this->getServiceLocationsWithHttpInfo($carrier_name, $lat, $lon, $service_location_type, $radius, $skip, $limit);
        return $response;
    }

    /**
     * Operation getServiceLocationsWithHttpInfo
     *
     * Return a list of service locations, optionally filter by location type and/or within a radius of a given point
     *
     * @param  string $carrier_name The carrier ID for which to provide a list of available services. (optional)
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon &amp; radius. (optional)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat &amp; radius. (optional)
     * @param  string $service_location_type The type of service location (e.g. Agent, Depot). (optional)
     * @param  int $radius The distance in metres from the geo point the service point must be within. Requires lat &amp; lon. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ServiceLocations, HTTP status code, HTTP response headers (array of strings)
     */
    public function getServiceLocationsWithHttpInfo($carrier_name = null, $lat = null, $lon = null, $service_location_type = null, $radius = null, $skip = '0', $limit = '10')
    {
        $returnType = '\Swagger\Client\Model\ServiceLocations';
        $request = $this->getServiceLocationsRequest($carrier_name, $lat, $lon, $service_location_type, $radius, $skip, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ServiceLocations',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getServiceLocationsAsync
     *
     * Return a list of service locations, optionally filter by location type and/or within a radius of a given point
     *
     * @param  string $carrier_name The carrier ID for which to provide a list of available services. (optional)
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon &amp; radius. (optional)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat &amp; radius. (optional)
     * @param  string $service_location_type The type of service location (e.g. Agent, Depot). (optional)
     * @param  int $radius The distance in metres from the geo point the service point must be within. Requires lat &amp; lon. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getServiceLocationsAsync($carrier_name = null, $lat = null, $lon = null, $service_location_type = null, $radius = null, $skip = '0', $limit = '10')
    {
        return $this->getServiceLocationsAsyncWithHttpInfo($carrier_name, $lat, $lon, $service_location_type, $radius, $skip, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getServiceLocationsAsyncWithHttpInfo
     *
     * Return a list of service locations, optionally filter by location type and/or within a radius of a given point
     *
     * @param  string $carrier_name The carrier ID for which to provide a list of available services. (optional)
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon &amp; radius. (optional)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat &amp; radius. (optional)
     * @param  string $service_location_type The type of service location (e.g. Agent, Depot). (optional)
     * @param  int $radius The distance in metres from the geo point the service point must be within. Requires lat &amp; lon. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getServiceLocationsAsyncWithHttpInfo($carrier_name = null, $lat = null, $lon = null, $service_location_type = null, $radius = null, $skip = '0', $limit = '10')
    {
        $returnType = '\Swagger\Client\Model\ServiceLocations';
        $request = $this->getServiceLocationsRequest($carrier_name, $lat, $lon, $service_location_type, $radius, $skip, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getServiceLocations'
     *
     * @param  string $carrier_name The carrier ID for which to provide a list of available services. (optional)
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon &amp; radius. (optional)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat &amp; radius. (optional)
     * @param  string $service_location_type The type of service location (e.g. Agent, Depot). (optional)
     * @param  int $radius The distance in metres from the geo point the service point must be within. Requires lat &amp; lon. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getServiceLocationsRequest($carrier_name = null, $lat = null, $lon = null, $service_location_type = null, $radius = null, $skip = '0', $limit = '10')
    {

        $resourcePath = '/v1/service-locations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($carrier_name !== null) {
            $queryParams['carrierName'] = ObjectSerializer::toQueryValue($carrier_name, null);
        }
        // query params
        if ($lat !== null) {
            $queryParams['lat'] = ObjectSerializer::toQueryValue($lat, 'double');
        }
        // query params
        if ($lon !== null) {
            $queryParams['lon'] = ObjectSerializer::toQueryValue($lon, 'double');
        }
        // query params
        if ($service_location_type !== null) {
            $queryParams['serviceLocationType'] = ObjectSerializer::toQueryValue($service_location_type, null);
        }
        // query params
        if ($radius !== null) {
            $queryParams['radius'] = ObjectSerializer::toQueryValue($radius, null);
        }
        // query params
        if ($skip !== null) {
            $queryParams['skip'] = ObjectSerializer::toQueryValue($skip, 'int32');
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit, 'int32');
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getServices
     *
     * Finds available services for a given query
     *
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon. (required)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat. (required)
     * @param  string $carrier_name The carrier ID for which to provide a list of available services.  If not provided all carriers will be returned. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CarrierServices
     */
    public function getServices($lat, $lon, $carrier_name = null)
    {
        list($response) = $this->getServicesWithHttpInfo($lat, $lon, $carrier_name);
        return $response;
    }

    /**
     * Operation getServicesWithHttpInfo
     *
     * Finds available services for a given query
     *
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon. (required)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat. (required)
     * @param  string $carrier_name The carrier ID for which to provide a list of available services.  If not provided all carriers will be returned. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CarrierServices, HTTP status code, HTTP response headers (array of strings)
     */
    public function getServicesWithHttpInfo($lat, $lon, $carrier_name = null)
    {
        $returnType = '\Swagger\Client\Model\CarrierServices';
        $request = $this->getServicesRequest($lat, $lon, $carrier_name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CarrierServices',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getServicesAsync
     *
     * Finds available services for a given query
     *
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon. (required)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat. (required)
     * @param  string $carrier_name The carrier ID for which to provide a list of available services.  If not provided all carriers will be returned. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getServicesAsync($lat, $lon, $carrier_name = null)
    {
        return $this->getServicesAsyncWithHttpInfo($lat, $lon, $carrier_name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getServicesAsyncWithHttpInfo
     *
     * Finds available services for a given query
     *
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon. (required)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat. (required)
     * @param  string $carrier_name The carrier ID for which to provide a list of available services.  If not provided all carriers will be returned. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getServicesAsyncWithHttpInfo($lat, $lon, $carrier_name = null)
    {
        $returnType = '\Swagger\Client\Model\CarrierServices';
        $request = $this->getServicesRequest($lat, $lon, $carrier_name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getServices'
     *
     * @param  double $lat The latitude for which to provide a list of available services. Requires lon. (required)
     * @param  double $lon The longitude for which to provide a list of available services. Requires lat. (required)
     * @param  string $carrier_name The carrier ID for which to provide a list of available services.  If not provided all carriers will be returned. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getServicesRequest($lat, $lon, $carrier_name = null)
    {
        // verify the required parameter 'lat' is set
        if ($lat === null || (is_array($lat) && count($lat) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lat when calling getServices'
            );
        }
        // verify the required parameter 'lon' is set
        if ($lon === null || (is_array($lon) && count($lon) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lon when calling getServices'
            );
        }

        $resourcePath = '/v1/services';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($lat !== null) {
            $queryParams['lat'] = ObjectSerializer::toQueryValue($lat, 'double');
        }
        // query params
        if ($lon !== null) {
            $queryParams['lon'] = ObjectSerializer::toQueryValue($lon, 'double');
        }
        // query params
        if ($carrier_name !== null) {
            $queryParams['carrierName'] = ObjectSerializer::toQueryValue($carrier_name, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
