<?php
/**
 * TrackingEventsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * TrackingEventsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TrackingEventsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getTrackingEvents
     *
     * Finds tracking events by using query string parameters
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  \DateTime $events_from When searching within a date range, this is the start time which you want to search from. (optional)
     * @param  \DateTime $events_to When searching within a date range, this is the end time which you want to search to. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\TrackingEvents
     */
    public function getTrackingEvents($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from = null, $events_to = null, $skip = '0', $limit = '10')
    {
        list($response) = $this->getTrackingEventsWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from, $events_to, $skip, $limit);
        return $response;
    }

    /**
     * Operation getTrackingEventsWithHttpInfo
     *
     * Finds tracking events by using query string parameters
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  \DateTime $events_from When searching within a date range, this is the start time which you want to search from. (optional)
     * @param  \DateTime $events_to When searching within a date range, this is the end time which you want to search to. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\TrackingEvents, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTrackingEventsWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from = null, $events_to = null, $skip = '0', $limit = '10')
    {
        $returnType = '\Swagger\Client\Model\TrackingEvents';
        $request = $this->getTrackingEventsRequest($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from, $events_to, $skip, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\TrackingEvents',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTrackingEventsAsync
     *
     * Finds tracking events by using query string parameters
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  \DateTime $events_from When searching within a date range, this is the start time which you want to search from. (optional)
     * @param  \DateTime $events_to When searching within a date range, this is the end time which you want to search to. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTrackingEventsAsync($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from = null, $events_to = null, $skip = '0', $limit = '10')
    {
        return $this->getTrackingEventsAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from, $events_to, $skip, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTrackingEventsAsyncWithHttpInfo
     *
     * Finds tracking events by using query string parameters
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  \DateTime $events_from When searching within a date range, this is the start time which you want to search from. (optional)
     * @param  \DateTime $events_to When searching within a date range, this is the end time which you want to search to. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTrackingEventsAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from = null, $events_to = null, $skip = '0', $limit = '10')
    {
        $returnType = '\Swagger\Client\Model\TrackingEvents';
        $request = $this->getTrackingEventsRequest($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from, $events_to, $skip, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTrackingEvents'
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  \DateTime $events_from When searching within a date range, this is the start time which you want to search from. (optional)
     * @param  \DateTime $events_to When searching within a date range, this is the end time which you want to search to. (optional)
     * @param  int $skip number of records to skip for pagination (optional, default to 0)
     * @param  int $limit maximum number of records to return (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getTrackingEventsRequest($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $events_from = null, $events_to = null, $skip = '0', $limit = '10')
    {
        // verify the required parameter 'carrier_name' is set
        if ($carrier_name === null || (is_array($carrier_name) && count($carrier_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_name when calling getTrackingEvents'
            );
        }
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling getTrackingEvents'
            );
        }
        // verify the required parameter 'consignment_id' is set
        if ($consignment_id === null || (is_array($consignment_id) && count($consignment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consignment_id when calling getTrackingEvents'
            );
        }
        // verify the required parameter 'consignment_item_id' is set
        if ($consignment_item_id === null || (is_array($consignment_item_id) && count($consignment_item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consignment_item_id when calling getTrackingEvents'
            );
        }

        $resourcePath = '/v1/carriers/{carrierName}/customers/{customerId}/consignments/{consignmentId}/items/{consignmentItemId}/tracking-events';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($events_from !== null) {
            $queryParams['eventsFrom'] = ObjectSerializer::toQueryValue($events_from, 'date-time');
        }
        // query params
        if ($events_to !== null) {
            $queryParams['eventsTo'] = ObjectSerializer::toQueryValue($events_to, 'date-time');
        }
        // query params
        if ($skip !== null) {
            $queryParams['skip'] = ObjectSerializer::toQueryValue($skip, 'int32');
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit, 'int32');
        }

        // path params
        if ($carrier_name !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierName' . '}',
                ObjectSerializer::toPathValue($carrier_name),
                $resourcePath
            );
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }
        // path params
        if ($consignment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consignmentId' . '}',
                ObjectSerializer::toPathValue($consignment_id),
                $resourcePath
            );
        }
        // path params
        if ($consignment_item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consignmentItemId' . '}',
                ObjectSerializer::toPathValue($consignment_item_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTrackingEventsAttachment
     *
     * Finds attachment for a tracking event
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  string $collection_id Collection Id (required)
     * @param  string $image_id Image Id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function getTrackingEventsAttachment($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id)
    {
        list($response) = $this->getTrackingEventsAttachmentWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id);
        return $response;
    }

    /**
     * Operation getTrackingEventsAttachmentWithHttpInfo
     *
     * Finds attachment for a tracking event
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  string $collection_id Collection Id (required)
     * @param  string $image_id Image Id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTrackingEventsAttachmentWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id)
    {
        $returnType = 'string';
        $request = $this->getTrackingEventsAttachmentRequest($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTrackingEventsAttachmentAsync
     *
     * Finds attachment for a tracking event
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  string $collection_id Collection Id (required)
     * @param  string $image_id Image Id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTrackingEventsAttachmentAsync($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id)
    {
        return $this->getTrackingEventsAttachmentAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTrackingEventsAttachmentAsyncWithHttpInfo
     *
     * Finds attachment for a tracking event
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  string $collection_id Collection Id (required)
     * @param  string $image_id Image Id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTrackingEventsAttachmentAsyncWithHttpInfo($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id)
    {
        $returnType = 'string';
        $request = $this->getTrackingEventsAttachmentRequest($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTrackingEventsAttachment'
     *
     * @param  string $carrier_name Freightways Carrier (required)
     * @param  string $customer_id Carrier Customer Id (required)
     * @param  string $consignment_id Consignment Id (required)
     * @param  string $consignment_item_id Consignment Item Id (required)
     * @param  string $collection_id Collection Id (required)
     * @param  string $image_id Image Id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getTrackingEventsAttachmentRequest($carrier_name, $customer_id, $consignment_id, $consignment_item_id, $collection_id, $image_id)
    {
        // verify the required parameter 'carrier_name' is set
        if ($carrier_name === null || (is_array($carrier_name) && count($carrier_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_name when calling getTrackingEventsAttachment'
            );
        }
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling getTrackingEventsAttachment'
            );
        }
        // verify the required parameter 'consignment_id' is set
        if ($consignment_id === null || (is_array($consignment_id) && count($consignment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consignment_id when calling getTrackingEventsAttachment'
            );
        }
        // verify the required parameter 'consignment_item_id' is set
        if ($consignment_item_id === null || (is_array($consignment_item_id) && count($consignment_item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consignment_item_id when calling getTrackingEventsAttachment'
            );
        }
        // verify the required parameter 'collection_id' is set
        if ($collection_id === null || (is_array($collection_id) && count($collection_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $collection_id when calling getTrackingEventsAttachment'
            );
        }
        // verify the required parameter 'image_id' is set
        if ($image_id === null || (is_array($image_id) && count($image_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $image_id when calling getTrackingEventsAttachment'
            );
        }

        $resourcePath = '/v1/carriers/{carrierName}/customers/{customerId}/consignments/{consignmentId}/items/{consignmentItemId}/tracking-events/attachments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($collection_id !== null) {
            $queryParams['collectionId'] = ObjectSerializer::toQueryValue($collection_id, null);
        }
        // query params
        if ($image_id !== null) {
            $queryParams['imageId'] = ObjectSerializer::toQueryValue($image_id, null);
        }

        // path params
        if ($carrier_name !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierName' . '}',
                ObjectSerializer::toPathValue($carrier_name),
                $resourcePath
            );
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }
        // path params
        if ($consignment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consignmentId' . '}',
                ObjectSerializer::toPathValue($consignment_id),
                $resourcePath
            );
        }
        // path params
        if ($consignment_item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consignmentItemId' . '}',
                ObjectSerializer::toPathValue($consignment_item_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/jpeg', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/jpeg', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
