<?php
/**
 * BasePlusItemRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BasePlusItemRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Defines a base plus consignment item. Customer must have base plus rates configured and provide either weight or volume
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BasePlusItemRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BasePlusItemRequest"
     */
    public function testBasePlusItemRequest()
    {
    }

    /**
     * Test attribute "item_reference"
     */
    public function testPropertyItemReference()
    {
    }

    /**
     * Test attribute "total_items"
     */
    public function testPropertyTotalItems()
    {
    }

    /**
     * Test attribute "total_weight"
     */
    public function testPropertyTotalWeight()
    {
    }

    /**
     * Test attribute "total_volume"
     */
    public function testPropertyTotalVolume()
    {
    }
}
