<?php
/**
 * ConsignmentItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConsignmentItemTest Class Doc Comment
 *
 * @category    Class
 * @description Defines the consignment item with calculated charges
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConsignmentItem"
     */
    public function testConsignmentItem()
    {
    }

    /**
     * Test attribute "consignment_item_id"
     */
    public function testPropertyConsignmentItemId()
    {
    }

    /**
     * Test attribute "item_reference"
     */
    public function testPropertyItemReference()
    {
    }

    /**
     * Test attribute "rate_service_code"
     */
    public function testPropertyRateServiceCode()
    {
    }

    /**
     * Test attribute "satchel_type"
     */
    public function testPropertySatchelType()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "pickup_date_time"
     */
    public function testPropertyPickupDateTime()
    {
    }

    /**
     * Test attribute "onboard_date_time"
     */
    public function testPropertyOnboardDateTime()
    {
    }

    /**
     * Test attribute "delivery_date_time"
     */
    public function testPropertyDeliveryDateTime()
    {
    }

    /**
     * Test attribute "total_rate_breakdown"
     */
    public function testPropertyTotalRateBreakdown()
    {
    }
}
