<?php
/**
 * ConsignmentRequestResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConsignmentRequestResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Defines a group of items to deliver
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentRequestResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConsignmentRequestResponse"
     */
    public function testConsignmentRequestResponse()
    {
    }

    /**
     * Test attribute "warnings"
     */
    public function testPropertyWarnings()
    {
    }

    /**
     * Test attribute "consignment_id"
     */
    public function testPropertyConsignmentId()
    {
    }

    /**
     * Test attribute "calculated_charge_excluding_gst"
     */
    public function testPropertyCalculatedChargeExcludingGst()
    {
    }

    /**
     * Test attribute "gst"
     */
    public function testPropertyGst()
    {
    }

    /**
     * Test attribute "calculated_charge_including_gst"
     */
    public function testPropertyCalculatedChargeIncludingGst()
    {
    }

    /**
     * Test attribute "customer_references"
     */
    public function testPropertyCustomerReferences()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "saturday_delivery"
     */
    public function testPropertySaturdayDelivery()
    {
    }

    /**
     * Test attribute "no_split_delivery"
     */
    public function testPropertyNoSplitDelivery()
    {
    }
}
