<?php
/**
 * ConsignmentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConsignmentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Defines a group of items to deliver&lt;br/&gt;The total number of items (including each piece of a base plus item) must not exceed 99.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConsignmentRequest"
     */
    public function testConsignmentRequest()
    {
    }

    /**
     * Test attribute "signature_required"
     */
    public function testPropertySignatureRequired()
    {
    }

    /**
     * Test attribute "saturday_delivery"
     */
    public function testPropertySaturdayDelivery()
    {
    }

    /**
     * Test attribute "no_split_delivery"
     */
    public function testPropertyNoSplitDelivery()
    {
    }

    /**
     * Test attribute "consignment_reference"
     */
    public function testPropertyConsignmentReference()
    {
    }

    /**
     * Test attribute "consignment_date"
     */
    public function testPropertyConsignmentDate()
    {
    }

    /**
     * Test attribute "service_standard"
     */
    public function testPropertyServiceStandard()
    {
    }

    /**
     * Test attribute "sequence_id"
     */
    public function testPropertySequenceId()
    {
    }

    /**
     * Test attribute "notifications"
     */
    public function testPropertyNotifications()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "receiver"
     */
    public function testPropertyReceiver()
    {
    }

    /**
     * Test attribute "customer_references"
     */
    public function testPropertyCustomerReferences()
    {
    }

    /**
     * Test attribute "standard_items"
     */
    public function testPropertyStandardItems()
    {
    }

    /**
     * Test attribute "base_plus_items"
     */
    public function testPropertyBasePlusItems()
    {
    }

    /**
     * Test attribute "satchel_items"
     */
    public function testPropertySatchelItems()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }
}
