<?php
/**
 * RatesRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RatesRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Consignment details required in order for it to be rated.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RatesRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RatesRequest"
     */
    public function testRatesRequest()
    {
    }

    /**
     * Test attribute "pickup_address"
     */
    public function testPropertyPickupAddress()
    {
    }

    /**
     * Test attribute "delivery_address"
     */
    public function testPropertyDeliveryAddress()
    {
    }

    /**
     * Test attribute "signature_required"
     */
    public function testPropertySignatureRequired()
    {
    }

    /**
     * Test attribute "saturday_delivery"
     */
    public function testPropertySaturdayDelivery()
    {
    }

    /**
     * Test attribute "txt_notification"
     */
    public function testPropertyTxtNotification()
    {
    }

    /**
     * Test attribute "service_standard"
     */
    public function testPropertyServiceStandard()
    {
    }

    /**
     * Test attribute "standard_items"
     */
    public function testPropertyStandardItems()
    {
    }

    /**
     * Test attribute "base_plus_items"
     */
    public function testPropertyBasePlusItems()
    {
    }

    /**
     * Test attribute "satchel_items"
     */
    public function testPropertySatchelItems()
    {
    }
}
