<?php
/**
 * AddressesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * AddressesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddressesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for findAddressAutocomplete
     *
     * Returns a list of fuzzy addresses, intended for providing suggestions as you type..
     *
     */
    public function testFindAddressAutocomplete()
    {
    }

    /**
     * Test case for findAddressFuzzy
     *
     * Fuzzy Search of Address data..
     *
     */
    public function testFindAddressFuzzy()
    {
    }

    /**
     * Test case for findAddressMatch
     *
     * Returns a list of fuzzy addresses, intended for providing suggestions as you type..
     *
     */
    public function testFindAddressMatch()
    {
    }

    /**
     * Test case for getAddressForId
     *
     * Returns a list of fuzzy addresses, intended for providing suggestions as you type..
     *
     */
    public function testGetAddressForId()
    {
    }
}
