<?php
/**
 * ConsignmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freightways Customer Integration
 *
 * Provisioning Freightways services as REST APIs
 *
 * OpenAPI spec version: 1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ConsignmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelConsignmentById
     *
     * Request cancellation of a Consignment by Id..
     *
     */
    public function testCancelConsignmentById()
    {
    }

    /**
     * Test case for getConsignmentById
     *
     * Consignment by Id..
     *
     */
    public function testGetConsignmentById()
    {
    }

    /**
     * Test case for getConsignmentsByParameters
     *
     * Search consignments based on Consignment / Sender / Receiver details.
     *
     */
    public function testGetConsignmentsByParameters()
    {
    }

    /**
     * Test case for postConsignment
     *
     * Upload consignment data..
     *
     */
    public function testPostConsignment()
    {
    }
}
